import { useState, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useSales, useMovements, useExpenses, useSuppliers } from "@/hooks/useInventoryData";
import { useDemo } from "@/hooks/useDemo";
import type { Item, Category } from "@/types/inventory";
import { DISTRIBUTOR_PRESETS } from "@/utils/categorySuggestions";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";
import {
  FileCheck,
  Printer,
  ShieldCheck,
  TrendingUp,
  AlertTriangle,
  Building2,
  Package,
  Wine,
  DollarSign,
  Calendar,
  CheckCircle2,
  FileSpreadsheet,
} from "lucide-react";

interface AuditComplianceSectionProps {
  items: Item[];
  categories: Category[];
}

export function AuditComplianceSection({ items, categories }: AuditComplianceSectionProps) {
  const { currentStore } = useDemo();
  const { data: sales = [] } = useSales();
  const { data: movements = [] } = useMovements();
  const { data: expenses = [] } = useExpenses();
  const { data: suppliers = [] } = useSuppliers();

  const [auditDate] = useState<string>(new Date().toLocaleDateString("en-NG", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  }));

  // Calculations
  const totalCostValuation = items.reduce((sum, item) => sum + (item.costPriceNgn || 0) * (item.currentStock || 0), 0);
  const totalRetailValuation = items.reduce((sum, item) => sum + (item.sellingPriceNgn || 0) * (item.currentStock || 0), 0);
  const totalPotentialProfit = totalRetailValuation - totalCostValuation;
  const grossMarginPercent = totalRetailValuation > 0 ? ((totalPotentialProfit / totalRetailValuation) * 100).toFixed(1) : "0.0";

  const totalSalesRevenue = sales.reduce((sum, s) => sum + (s.totalNgn || 0), 0);
  const totalExpensesAmount = expenses.reduce((sum, e) => sum + (e.amountNgn || 0), 0);
  const netProfit = totalSalesRevenue - totalExpensesAmount;

  const lowStockItems = items.filter((i) => (i.currentStock || 0) <= (i.minStockAlert || 5));
  const outOfStockItems = items.filter((i) => (i.currentStock || 0) <= 0);

  // Beverages specific audit
  const beverageCategory = categories.find(
    (c) => c.name.toLowerCase().includes("beverage") || c.name.toLowerCase().includes("drink")
  );
  const beverageItems = items.filter((i) => {
    if (beverageCategory && i.categoryId === beverageCategory.id) return true;
    const name = i.name.toLowerCase();
    return (
      name.includes("coke") ||
      name.includes("pepsi") ||
      name.includes("water") ||
      name.includes("drink") ||
      name.includes("beer") ||
      name.includes("cl") ||
      name.includes("liter") ||
      name.includes("juice") ||
      name.includes("malt") ||
      name.includes("stout")
    );
  });

  const totalBeverageUnits = beverageItems.reduce((sum, i) => sum + (i.currentStock || 0), 0);
  const beverageValuation = beverageItems.reduce((sum, i) => sum + (i.sellingPriceNgn || 0) * (i.currentStock || 0), 0);

  // PDF Generation with jsPDF & AutoTable
  const handleExportPDF = () => {
    try {
      const doc = new jsPDF();

      // Brand Header
      doc.setFillColor(13, 148, 136); // Emerald primary
      doc.rect(0, 0, 210, 32, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text(currentStore?.name || "STACKWISE ENTERPRISE", 14, 16);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("INVENTORY & FINANCIAL COMPLIANCE AUDIT REPORT", 14, 24);

      // Metadata
      doc.setTextColor(50, 50, 50);
      doc.setFontSize(9);
      doc.text(`Audit Date: ${auditDate}`, 14, 40);
      doc.text(`Store Location: ${currentStore?.state || "Lagos"}, Nigeria`, 14, 46);
      doc.text(`Generated By: System Auditor (Nexa Technologies)`, 14, 52);
      doc.text(`Status: VERIFIED & COMPLIANT`, 140, 40);

      // Executive Summary Table
      autoTable(doc, {
        startY: 58,
        head: [["Audit Key Performance Indicator", "Audit Value (NGN / Count)", "Compliance Status"]],
        body: [
          ["Total Stock Cost Valuation", `NGN ${totalCostValuation.toLocaleString()}`, "Balanced"],
          ["Total Retail Sales Potential", `NGN ${totalRetailValuation.toLocaleString()}`, "Target Achieved"],
          ["Estimated Gross Margin", `${grossMarginPercent}%`, grossMarginPercent > "20" ? "Optimal" : "Review Pricing"],
          ["Total Sales Revenue Recorded", `NGN ${totalSalesRevenue.toLocaleString()}`, "Audited"],
          ["Total Expenses Incurred", `NGN ${totalExpensesAmount.toLocaleString()}`, "Recorded"],
          ["Estimated Net Operating Profit", `NGN ${netProfit.toLocaleString()}`, netProfit >= 0 ? "Profitable" : "Deficit"],
          ["Total Active SKU Items", `${items.length} SKUs`, "Reconciled"],
          ["Low Stock Alert Triggered", `${lowStockItems.length} items`, lowStockItems.length === 0 ? "Compliant" : "Reorder Needed"],
          ["Beverage & Liquid Stock Count", `${totalBeverageUnits} units (NGN ${beverageValuation.toLocaleString()})`, "Verified"],
        ],
        theme: "grid",
        headStyles: { fillColor: [13, 148, 136], textColor: 255, fontStyle: "bold" },
        styles: { fontSize: 9 },
      });

      // Item Valuation Breakdown Table
      const itemRows = items.slice(0, 25).map((item) => [
        item.name,
        item.unit || "pcs",
        item.currentStock || 0,
        `NGN ${(item.costPriceNgn || 0).toLocaleString()}`,
        `NGN ${(item.sellingPriceNgn || 0).toLocaleString()}`,
        `NGN ${((item.sellingPriceNgn || 0) * (item.currentStock || 0)).toLocaleString()}`,
      ]);

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const currentY = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : 120;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Stock Line Item Audit Breakdown (Top 25 SKUs)", 14, currentY);

      autoTable(doc, {
        startY: currentY + 4,
        head: [["Product Name", "Unit", "Stock", "Cost Price", "Selling Price", "Total Valuation"]],
        body: itemRows,
        theme: "striped",
        headStyles: { fillColor: [51, 65, 85], textColor: 255, fontStyle: "bold" },
        styles: { fontSize: 8 },
      });

      // Auditor Footer
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const finalY = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 20 : 200;
      if (finalY < 270) {
        doc.setDrawColor(200, 200, 200);
        doc.line(14, finalY, 80, finalY);
        doc.line(130, finalY, 196, finalY);

        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text("Store Manager Signature", 14, finalY + 5);
        doc.text("Internal/External Auditor Signature", 130, finalY + 5);
      }

      doc.save(`Audit_Report_${currentStore?.name.replace(/[^a-zA-Z0-9]/g, "_") || "Store"}_${new Date().toISOString().slice(0,10)}.pdf`);
      toast.success("Branded PDF Audit Report generated and downloaded!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF audit report.");
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <Card className="bg-gradient-to-r from-emerald-900/90 via-teal-900/80 to-slate-900 text-white border-none shadow-lg">
        <CardContent className="p-6 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2">
              <Badge className="bg-emerald-500/20 text-emerald-300 border-emerald-400/30 px-2.5 py-0.5 text-xs font-bold uppercase tracking-wider">
                <ShieldCheck className="h-3.5 w-3.5 mr-1 text-emerald-400" /> Official Compliance
              </Badge>
              <span className="text-xs text-emerald-200/80 font-mono">{auditDate}</span>
            </div>
            <h2 className="text-2xl font-bold tracking-tight text-white font-sans">
              Store Audit & Financial Ledger
            </h2>
            <p className="text-xs text-emerald-100/80 max-w-2xl">
              Consolidated audit section tracking asset cost valuations, gross margins, beverage volume logs, expense ratios, and verified supplier trails.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <Button
              onClick={() => window.print()}
              variant="outline"
              size="sm"
              className="bg-white/10 hover:bg-white/20 text-white border-white/20 text-xs font-bold"
            >
              <Printer className="h-4 w-4 mr-1.5" />
              Print View
            </Button>
            <Button
              onClick={handleExportPDF}
              size="sm"
              className="bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold shadow-md"
            >
              <FileCheck className="h-4 w-4 mr-1.5" />
              Export Branded PDF
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Audit Metric Cards */}
      <div className="grid gap-4 md:grid-cols-4 sm:grid-cols-2">
        <Card className="shadow-none border border-muted-foreground/15">
          <CardContent className="p-5 flex items-center justify-between">
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground font-semibold uppercase">Cost Asset Value</span>
              <p className="text-xl font-bold tracking-tight text-foreground">₦{totalCostValuation.toLocaleString()}</p>
              <span className="text-[10px] text-muted-foreground block">Inventory cost basis</span>
            </div>
            <div className="bg-blue-500/10 p-3 rounded-xl text-blue-600 dark:text-blue-400">
              <DollarSign className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-none border border-muted-foreground/15">
          <CardContent className="p-5 flex items-center justify-between">
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground font-semibold uppercase">Retail Asset Value</span>
              <p className="text-xl font-bold tracking-tight text-emerald-600 dark:text-emerald-400">
                ₦{totalRetailValuation.toLocaleString()}
              </p>
              <span className="text-[10px] text-emerald-500 font-bold block">
                +{grossMarginPercent}% Est. Margin
              </span>
            </div>
            <div className="bg-emerald-500/10 p-3 rounded-xl text-emerald-600 dark:text-emerald-400">
              <TrendingUp className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-none border border-muted-foreground/15">
          <CardContent className="p-5 flex items-center justify-between">
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground font-semibold uppercase">Drinks & Beverages</span>
              <p className="text-xl font-bold tracking-tight text-foreground">
                {totalBeverageUnits} <span className="text-xs font-normal text-muted-foreground">units</span>
              </p>
              <span className="text-[10px] text-muted-foreground block font-medium">
                Valued at ₦{beverageValuation.toLocaleString()}
              </span>
            </div>
            <div className="bg-purple-500/10 p-3 rounded-xl text-purple-600 dark:text-purple-400">
              <Wine className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-none border border-muted-foreground/15">
          <CardContent className="p-5 flex items-center justify-between">
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground font-semibold uppercase">Audit Discrepancies</span>
              <p className="text-xl font-bold tracking-tight text-amber-600 dark:text-amber-400">
                {lowStockItems.length + outOfStockItems.length} <span className="text-xs font-normal text-muted-foreground">alerts</span>
              </p>
              <span className="text-[10px] text-amber-500 font-bold block">
                {outOfStockItems.length} Critical Out of Stock
              </span>
            </div>
            <div className="bg-amber-500/10 p-3 rounded-xl text-amber-600 dark:text-amber-400">
              <AlertTriangle className="h-5 w-5" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Detailed Audit Decks */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Drinks & Beverages Specific Audit Section */}
        <Card className="shadow-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Wine className="h-5 w-5 text-purple-500" />
                <CardTitle className="text-base font-bold">Beverages & Drinks Variety Audit</CardTitle>
              </div>
              <Badge variant="secondary" className="text-[10px]">
                {beverageItems.length} Beverage SKUs
              </Badge>
            </div>
            <CardDescription className="text-xs">
              Audit logs for liquid volume SKUs (50cl, 33cl, 75cl, 1L) and crate/bottle unit counts
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <div className="border-t max-h-[280px] overflow-y-auto">
              <Table>
                <TableHeader>
                  <TableRow className="text-[11px]">
                    <TableHead>Drink Product</TableHead>
                    <TableHead>Unit / Vol</TableHead>
                    <TableHead className="text-right">In Stock</TableHead>
                    <TableHead className="text-right">Valuation</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {beverageItems.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center py-6 text-xs text-muted-foreground">
                        No beverage items registered. Add Coca-Cola, Maltina, or Water in Quick Entry to see them here.
                      </TableCell>
                    </TableRow>
                  ) : (
                    beverageItems.map((item) => (
                      <TableRow key={item.id} className="text-xs">
                        <TableCell className="font-semibold">{item.name}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className="text-[10px] uppercase font-mono px-1.5 py-0">
                            {item.unit || "bottle"}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right font-bold">{item.currentStock || 0}</TableCell>
                        <TableCell className="text-right font-mono text-emerald-600 dark:text-emerald-400 font-bold">
                          ₦{((item.sellingPriceNgn || 0) * (item.currentStock || 0)).toLocaleString()}
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>

        {/* Verified Distributors Audit Trail */}
        <Card className="shadow-sm">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Building2 className="h-5 w-5 text-blue-500" />
                <CardTitle className="text-base font-bold">Verified Distributors Audit Trail</CardTitle>
              </div>
              <Badge variant="secondary" className="text-[10px]">
                {suppliers.length} Store Suppliers
              </Badge>
            </div>
            <CardDescription className="text-xs">
              Audit of connected supplier depots, lead times, and active procurement links
            </CardDescription>
          </CardHeader>
          <CardContent className="p-0">
            <div className="border-t max-h-[280px] overflow-y-auto">
              <Table>
                <TableHeader>
                  <TableRow className="text-[11px]">
                    <TableHead>Distributor Name</TableHead>
                    <TableHead>Contact Lead</TableHead>
                    <TableHead className="text-right">Lead Time</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {suppliers.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={4} className="text-center py-6 text-xs text-muted-foreground">
                        No active suppliers attached. Import verified depots from the Supplier Directory.
                      </TableCell>
                    </TableRow>
                  ) : (
                    suppliers.map((sup) => (
                      <TableRow key={sup.id} className="text-xs">
                        <TableCell className="font-semibold">
                          {sup.name}
                          {sup.notes?.includes("Official Verified Distributor") && (
                            <Badge variant="outline" className="ml-1.5 text-[9px] bg-emerald-500/10 text-emerald-600 border-emerald-500/20 px-1 py-0">
                              Verified Depot
                            </Badge>
                          )}
                        </TableCell>
                        <TableCell className="text-muted-foreground">{sup.contactName || sup.phone || "—"}</TableCell>
                        <TableCell className="text-right font-medium">{sup.leadTimeDays || 1} day(s)</TableCell>
                        <TableCell className="text-right">
                          <Badge variant="outline" className="text-[10px] bg-emerald-500/10 text-emerald-600 border-emerald-500/20">
                            Active
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
